mechanic/urls.py
from django.urls import path
from . import views
from .views import RequestPasswordResetEmail, PasswordReset
from django.contrib.auth import views as auth_views


app_name = 'mechanic'

urlpatterns=[

    path('', views.dashboard, name='dashboard'),
    path('profile', views.profile, name='profile'),
    path('read_all_notifications/', views.read_all_notifications, name='read_all_notifications'),
    path('password-update/', views.password_update, name='password_update'),
    path('user-info-update/', views.user_info_update, name='user_info_update'),
    path('notification-logs/',views.notification_logs, name='notification_logs'),
    path(r'set-new-password/<uidb64>/<token>',PasswordReset.as_view(),name='new-password'),
    path(r'password-reset',RequestPasswordResetEmail.as_view(),name="password-reset"),

]

mechanic_webapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mymodels.urls',namespace='mymodels')),
    path('mechanic/',include('mechanic.urls',namespace='mechanic')),
    path('car/',include('car_owner.urls',namespace='car_owner')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mymodels/urls.py
from django.urls import path
from . import views


app_name = 'mymodels'

urlpatterns=[
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('logout_view/', views.logout_view, name='logout_view'),
    path('accounts/login/', views.login_view, name='login_view'),
]

mechanic/models.py
from django.db import models

# Create your models here.

mechanic/forms.py
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from mymodels.models import Custom_User
from django import forms

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = Custom_User
        fields = ("last_name", "email","first_name","profile")

        widgets = {
            'last_name': forms.TextInput(attrs={'class': 'input-field'}),
            'email': forms.EmailInput(attrs={'class': 'input-field','required':'required'}),
            'first_name': forms.TextInput(attrs={'class': 'input-field'}),
            'profile': forms.FileInput(attrs={'class': 'input-field'}),            
        }

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Add class attributes to individual input widgets
        self.fields['old_password'].widget.attrs.update({'class': 'input-field'})
        self.fields['new_password1'].widget.attrs.update({'class': 'input-field'})
        self.fields['new_password2'].widget.attrs.update({'class': 'input-field'})

mechanic/views.py
from django.shortcuts import render,redirect
from mymodels.models import Request, Notification
from django.contrib.auth.password_validation import validate_password, MinimumLengthValidator, CommonPasswordValidator
from django.contrib import messages
from .forms  import CustomUserChangeForm
from django.views import View
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives,EmailMessage
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from django.urls import reverse
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from mymodels.models import *
import threading


# Create your views here.


class EmailThread(threading.Thread):
    '''Use this class to send emails on different thread so that application does not hold memory and CPU resoucees
        while waiting for the SMTP server to respond 
    '''
    def __init__(self, email):
        self.email = email
        threading.Thread.__init__(self)

    def run(self):
        self.email.send(fail_silently=False)



@login_required
def dashboard(request):
    myrequests = Request.objects.filter(user=request.user)
    
    print(myrequests)
    return render(request,"mechanic/dashboard.html",{'myrequests':myrequests})



@login_required
def user_info_update(request):
    info_form = CustomUserChangeForm(instance=request.user)
    if request.method == 'POST':
        info_form = CustomUserChangeForm(request.POST,request.FILES,instance=request.user)
        if info_form.is_valid():
            info_form.save()
            messages.success(request, 'information set successfully')
            if not request.user.date_joined:
                return redirect('mechanic:password_update')
            return redirect(request.META.get('HTTP_REFERER', '/'))
            
        messages.error(request, 'Update failed. Please try again')
    context = {'info_form':info_form}
    return render(request,'mechanic/user_info_update.html',context)
    
@login_required
def profile(request):
    return render(request,"mechanic/profile.html")

@login_required
def notification_logs(request):
    notification = Notification.objects.filter(user=request.user)
    return render(request,"mechanic/notificationlog.html",{'notification':notification})



class RequestPasswordResetEmail(View):
   
    def get(self,request):

        return render(request,'mechanic/password_reset.html')

    def post(self,request):
        
        email = request.POST['email']

        context = {'values':request.POST,}

        current_site=get_current_site(request)
        try:
            user = Custom_User.objects.filter(email=str(email))
            print(user[0])
            if user:
                email_contents ={
                'user':user[0],
                'domain':current_site.domain,
                'uidb64': urlsafe_base64_encode(force_bytes(user[0].pk)),
                'token':PasswordResetTokenGenerator().make_token(user[0]),
                }
                link = reverse('mechanic:new-password',kwargs = {'uidb64': email_contents['uidb64'], 'token': email_contents['token']})

                email_subject = 'Invoice Tracker: Password Reset Request'
                reset_url = 'http://'+current_site.domain+link

                merge_data = { 
                                    
                            'Account':user[0],
                        
                            'reset_link':reset_url
                        }
                               
                text_body = render_to_string("mechanic/passwordresetmail.txt", merge_data)
                html_body = render_to_string("mechanic/passwordResetMail.html", merge_data)
                # print(f'sending mail to {user[0].email}')
                msg = EmailMultiAlternatives(email_subject,text_body, from_email="helpdesk@psiug.org",
                        to=[user[0].email])
                msg.attach_alternative(html_body, "text/html")
                EmailThread(msg).start()
                messages.success(request, 'Password reset link has been sent, Check your email')

                return render(request,'mechanic/password_reset.html',context)
            else:
                messages.error(request, f"Account with specified email does not exist")
                return render(request,'mechanic/password_reset.html',context)
        except Exception as e:
            messages.error(request, f"Contact Systems Administrator: \n\n {e}")
            return render(request,'mechanic/password_reset.html',context)
        


@login_required
def password_update(request):
    if request.method == 'POST':        
        old_password = request.POST.get("old_password")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        try:
            validate_password(password1, user=request.user, password_validators=[MinimumLengthValidator(), CommonPasswordValidator()])
            user = authenticate(username=request.user, password=old_password)
            if user == request.user:
                if password1 == password2:
                    actual_user = request.user
                    actual_user.set_password(password1)
                    actual_user.save()
                    messages.success(request,"Login with your new password")
                    return redirect("mymodels:logout_view")
                else:
                    messages.error(request,"the re-ented password doesn't match")
                    return redirect(request.META.get('HTTP_REFERER'))
            else:
                messages.error(request,"wrong old password")
                return redirect(request.META.get('HTTP_REFERER'))

        except Exception as e:
            for err in e:
                messages.error(request, err)
            return redirect(request.META.get('HTTP_REFERER'))     
    return render(request,'mechanic/password_update.html')


def read_all_notifications(request):
    user = request.user
    notification = Notification.objects.filter(user=user, read=False)
    for notifi in notification:
        notifi.is_read = True
        notifi.save()
    return redirect(request.META.get('HTTP_REFERER'))


class PasswordReset(View):

    def get(self, request, uidb64, token):

        context = {
            'uidb64':uidb64,
            'token':token 
                   }
        try:
            user_id=force_str(urlsafe_base64_decode(uidb64))

            print(user_id)

            user = Custom_User.objects.get(pk=user_id)
            
            if not PasswordResetTokenGenerator().check_token(user, token):
                messages.info(request, "Password Reset Link already used. Please request for new link")
                return redirect('mymodels:login_view')
        except Exception as e:
            messages.info(request,"Password Reset Failed.")
            
            return render(request, 'mechanic/set-new-password.html', context)

        return render(request, 'mechanic/set-new-password.html', context)
    
    def post(self, request, uidb64, token):
        context = {
            'uidb64':uidb64,
            'token':token 
                   }

        password = request.POST['password']
        password2 = request.POST['password1']
#
# Add more password checks on complexity. 
        if password != password2:
            messages.error(request, "Passwords do not match")
            return render(request, 'mechanic/set-new-password.html', context)
        if len(password) < 6:
            messages.error(request, "Password should be longer than 6 Characters")
            return render(request, 'mechanic/set-new-password.html', context)
        
        try:
            user_id=force_str(urlsafe_base64_decode(uidb64))
            user = Custom_User.objects.get(pk=user_id)
            print(user.last_name)
            print(password)
            user.set_password(password)
            user.save()
            messages.success(request,"Your Password has been reset successfully")
            return redirect('mechanic:login_view')
        except Exception as e:
            messages.info(request,"Password Reset Failed. Contact Head Of Finance or Systems Administrator")
            print(f'Error is {e}')
            return render(request, 'mechanic/set-new-password.html', context)

mechanic/templates/mechanic/account.html
<div class="bread-crumb">
    <div class="cont">              
        <span>Edit Account Password</span>                
    </div>
</div>
 <div class="add-user">
    <div class="cont-card">
        <div class="head">
            <h3>Edit password</h3>
        </div>
        <div class="content">
            <form action="" class="form">
                <div class="form-group">
                    <div class="mb-3">
                        <label for="username" class="form-label">User Name</label>
                        <input type="text" class="form-control" >
                      </div>
                      <div class="mb-3">
                        <label for="password" class="form-label">old Password</label>
                        <input type="text" class="form-control" >
                      </div>
                      <div class="mb-3">
                        <label for="password" class="form-label"> New Password</label>
                        <input type="text" class="form-control" >
                      </div>
                      <div class="mb-3">
                        <label for="re-password" class="form-label">Re-Password</label>
                        <input type="password" class="form-control" >
                      </div>                     
                </div>
            </form>
        </div>
    </div>
                
 </div>

mechanic/templates/mechanic/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Mechanic Web app</title>
   <link rel="" href="images/psiug.png">

   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   <link href="https://unpkg.com/bootstrap-table@1.22.0/dist/bootstrap-table.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
   <link rel="stylesheet" href="{% static 'assets/styles/css/style.css' %}">
   


</head>

<body>
   {% block popup-model %} 

   {% endblock popup-model %}

   <div class="content-wrap" id="content-wrap">
      <!--msb: main sidebar-->
      <div>
         <div class="msb" id="msb">
            <div class="" role="navigation">
               <!-- Brand and toggle get grouped for better mobile display -->
               <div class="brand">
                  <div class="logo">
                     <img src="{% static 'assets/images/psiug.png' %}" alt="" />
                  </div>                  
               </div>

               <div class="user-info d-flex">
                  <div class="mx-auto">
                     <div class="pic">
                        {% if user.profile %}
                        <img src="{{ user.profile.url }}" alt="">
                        {% else %}
                        <img src="{% static 'assets/images/avator.png' %}" alt="">
                        {% endif %}
                     </div>
                     <div class="info">
                        <div>{{ user.first_name }} {{ user.last_name }}</div>
                        <div class="role">{{ user.username }}</div>
                     </div>
                  </div>
               </div>

               <!-- Main Menu -->
               <div class="side-menu" id="side-menu">
                <ul class="">
                    <li><a href="{% url 'mechanic:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                    <!-- Dropdown-->
                    <li class="dropdown">
                    <a class="dropdown" id="dropdown"><i class="fa fa-file-text-o" aria-hidden="true"></i>
                        Requests Management</a>
                    <div class="inner-menu" id="menu">
                        <ul class="">
                           
                           <li><a href=""><i class="fa fa-circle-o" aria-hidden="true"></i>View New request</a>
                           </li>
                            <li><a href=""><i class="fa fa-circle-o" aria-hidden="true"></i>View Past Requests</a>
                            </li>
                        </ul>
                    </div>
                    </li>
                    <li><a href="{% url 'mechanic:notification_logs' %}"><i class="fa fa-bell-o" aria-hidden="true"></i> Notification Logs</a></li>
                    <li><a href="{% url 'mechanic:profile' %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i></i> My Profile</a></li>
                    <li><a href="{% url 'mymodels:logout_view' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></li>
                </ul>
            </div>   
               <!-- /.navbar-collapse -->
            </div>
         </div>
         <div class="mobile-sb-close">
         </div>
      </div>
      <!-- end main side bar -->




      <!--main content wrapper-->
      <div class="mcw" id="mcw">
         <!--navigation here-->
         <!-- Top nav bar -->
         <div class="mnb">
            <div class="container-fluid top-navbar">
               <div class="my-auto">
                  <a href="#" id="msbo"><i class="ms-2 ic fa fa-bars"></i></a>
               </div>
               <div class="ms-auto my-auto d-flex">
                  <div class="notification">
                     <div class="notifi-numb" id="notifi-icon">
                        <i class="fa fa-bell-o" aria-hidden="true"></i>
                        <div>
                           <div></div>
                        </div>
                     </div>
                     <div class="notifi-drop notifi-hide">
                        <div class="notifi-head">
                           {% if unread_notifi|length != 0 %}
                           <div class="notifications">notifications <div class="number">{{ unread_notifi|length }}</div> <div class="ms-auto"><a href="{% url 'general:read_all_notifications' %}"> Read all </a></div></div>
                           {% else %}
                           <div class="notifications"> No notifications</div>
                           {% endif %}
                        </div>
                        <div class="content">
                           {% for notifi in unread_notifi %}
                              <div>
                                 <a href="{% url 'procurement:notification_act' pk=notifi.id %}">
                                    <div class="msg">{{ notifi.notification.message }}</div>
                                    <div class="time">{{ notifi.notification.created_at |timesince }} ago</div>
                                 </a>
                              </div>   
                           {% endfor %}
                        </div>
                     </div>
                  </div>

                  <div class="user">
                     <div class="profile-img" id="profile-img">
                        {% if user.profile %}
                        <img src="{{ user.profile.url }}" alt="">
                        {% else %}
                        <img src="{% static 'assets/images/avator.png' %}" alt="">
                        {% endif %}
                     </div>

                     <div class="my-drop hide">
                        <div class="container-fluid">
                           <div class="item"><a href=""><span class="fa fa-address-book-o"></span>account</a></div>
                           <div class="item"><a href="{% url 'mechanic:profile' %}"><span class="fa fa-user-circle-o"></span>Profile</a></div>
                           <div class="item"><a href="{% url 'mymodels:logout_view' %}"><span class="fa fa-sign-out"></span>logout</a></div>
                        </div>
                     </div>
                  </div>

               </div>
            </div>
         </div>
         <!-- End of top nav bar -->
         <!--main content view-->

         <!-- Button trigger modal -->

 
         <main class="cv">
            {% block main-content %} 

            {% endblock main-content %}
         </main>
      </div>


   </div>
      




   <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"></script>
   <script src="{% static 'assets/scripts/scritp.js' %}"></script>
   <script src="{% static 'assets/scripts/profileScripts.js' %}"></script>
   <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

   <script>
      $(document).ready(function () {
           $('#invoices').DataTable();
       }); 

      $(document).ready(function () {
           $('#notifications-logs').DataTable();
       });  


   </script>

</body>

</html>

mechanic/templates/mechanic/password_reset.html
{% extends 'mechanic/layout2.html' %}
{% load static %}

{% block auth_content %}    
<div class="login-form">  
	
    <form method="post" action="{% url 'mechanic:password-reset' %}">
		<p> You are requesting for a password reset</p> 
        {% csrf_token %}
		{% for message in messages %}
        	<div class="text-center mb-3">
				{% if message.tags == 'error' %}
					<small  class="text-light bg-danger">{{message}}</small >
				{% endif %}
				{% if message.tags == 'warning' %}
					<small  class="text-light bg-warning">{{message}}</small >
				{% endif %}
				{% if message.tags == 'success' %}
					<small  class="text-light bg-success">{{message}}</small >
				{% endif %}
			</div>                 
		{% endfor %}
        <div class="form-group mb-3">
            <div class="input-group">
                <div class="input-group-text">
                	<span class="fa fa-envelope"></span>
                </div>
				<input type="email" name="email" placeholder="Email..." class="form-control ", value="{{values.email}}"/>
            </div>
			<small class="form-text text-muted">Enter the email used at registration</small>
        </div>
        <div class="form-group">
            <button type="submit" class="btn mb-3">Send Request</button>
        </div>       
    </form>      
</div>
{% endblock %}

mechanic/templates/mechanic/password_update.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Login</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'assets/styles/css/login.css' %}">
</head>
<body>
  {% if messages.tags == "success" %}
        {% for message in messages %}
            <div class="toast-container position-fixed  bottom-0 end-0 p-3">
                <div id="liveToast" class="toast d-flex {% if message.tags %}{{ message.tags }}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true">          
                    <div class="toast-body">                
                        {{ message }}                        
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        {% endfor %} 
      {% endif %}

  <div class="wrapper">
    <div class="form-left">
        <h2 class="text-uppercase">Logged in as :{{ user }}</h2>
        <p>
          To Change password, fill in the old password or the one you have been provided with and your new password with atleast 8 characters
        </p>
        <p class="text">
            <span>Note:</span>
            On changing the password, you will be taken back to login page and you login with the newly changed password
        </p>
        <div class="form-field">
          <a href="{% url 'mechanic:dashboard' %}" class="green me-3 text-white">Go to Dashboard</a>
          <a href="{% url 'mechanic:user_info_update' %}" class="ms-3">Update user Info </a>
        </div>
    </div>
    <form method="POST" class="form-right">
      {% csrf_token %}
        <h2 class="text-uppercase">Change Password form</h2>
        {% if messages %}
          <ul class="messages mt-1">
              {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
      {% endif %}
        <div class="mb-3">
            <label>Old Password</label>
            <input type="password" class="input-field" name="old_password" required>
        </div>        
        <div class="mb-3">
            <label>New Password</label>
            <input type="password" class="input-field" name="password1" required>
        </div>        
        <div class="mb-3">
            <label>Re-enter New_password</label>
            <input type="password" class="input-field" name="password2" required>
        </div> 
        <div class="form-field">

            <input type="submit" value="Save" class="register">
        </div>
    </form>
</div>
</body>
</html>

mechanic/templates/mechanic/profile.html
{% extends 'mechanic/layout.html' %}
{% load static %}
{%block main-content %}

<div class="bread-crumb">
    <div class="cont">              
        <span>User Profile</span>              
    </div>
</div>
 <div class="cont-container">
    <div class="profile">
       <div class="cover">
       </div>
       <div class="image">
        {% if user.profile %}
        <img src="{{ user.profile.url }}" alt="">
        {% else %}
        <img src="{% static 'assets/images/avator.png' %}" alt="">
        {% endif %}
       </div>
       
       <div class="d-flex">
        <a href="{% url 'mechanic:user_info_update' %}" class="btn btn-success ms-auto">
            Edit account and password
        </a>
       </div>
       <div class="content">        
            <div class="tab">
                <div class="tablinks">User Profile</div>
                <button class="tablinks" onclick="opentab(event, 'personal')" id="defaultOpen">Personal</button>
                <button class="tablinks" onclick="opentab(event, 'performance')">Performance</button>
            </div>           
       
            <div id="personal" class="tabcontent">
                <h3>Personal</h3>
                <div class="details">
                    <form action="">
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="colFormLabel">Full Name</label>
                                <input type="email" class="form-control" disabled value="{{ user.first_name }} {{ user.last_name }}" /> 
                            </div>
                            <div class="col-md-6">
                                <label for="colFormLabel">Email</label>
                                <input type="email" class="form-control" disabled value="{{ user.email }}" /> 
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="colFormLabel">Work Time</label>
                                <input type="email" class="form-control" disabled value="{{ user.work_hours}}" /> 
                            </div>
                            <div class="col-md-6">
                                <label for="colFormLabel">Location</label>
                                <input type="email" class="form-control" disabled value="{{ user.location }}" /> 
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="colFormLabel">Added On</label>
                                <input type="email" class="form-control" disabled value="{{ user.date_joined}}" /> 
                            </div>
                            <div class="col-md-6">
                                <label for="colFormLabel">User Name</label>
                                <input type="email" class="form-control" disabled value="{{ user }}"> 
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div id="performance" class="tabcontent">
                <h3>Performance</h3>                
                <div class="details">
                    <form action="">
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="colFormLabel">Full Name</label>
                                <input type="email" class="form-control" disabled value="{{ user.first_name }} {{ user.last_name }}" /> 
                            </div>
                            <div class="col-md-6">
                                <label for="colFormLabel">My Rating</label>
                                <input type="email" class="form-control" disabled value="{{ user.location }}" />  
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="colFormLabel">work_hours</label>
                                <input type="email" class="form-control" disabled value="{{ user.work_hours }}" /> 
                            </div>
                            <div class="col-md-6">
                                <label for="colFormLabel">Experience</label>
                                <input type="email" class="form-control" disabled value="{{ user.experience }}" />  
                            </div>
                        </div>                
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock main-content %}

mechanic/templates/mechanic/toast_message.html
{% if messages %}
<div class="toast-container position-fixed top-0 end-0 mt-5">
    {% for message in messages %}
    <div 
    class="toast align-items-center {% if message.tags %}{{ message.tags }}{% endif %} border-0" 
    role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
          <div class="toast-body">
                <div class="text-white fw-bold">{{ message }}</div>            
          </div>
          <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>   
    {% endfor %}
</div>
{% endif %}